[Main]
RealAppId=4704690
FakeAppId=480

#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false


[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false


[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true


[EOSAuthWrapper]
DeviceIdAuth=true


[Hashes]
0=696bb7a5857ecce089cad34e40098c8564a3aad7081d7a4f5b13038963e67bbbed254b269c56d582a2432c7c696c9eb95b1cfb6e15117d0df90ed1f2bffe0b45