[Main]
RealAppId=1962700
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[EOSAuthWrapper]
DeviceIdAuth=true

[Hashes]
0=aef977bf8918fae4fcecc39349d2aa831bd2c902e768a0145d7d8b3256377ee405aa0818afb78013fe94528ff8ea6a9d472b5724fa109fd1539054e9c62dd740
